# Generated by Django 6.0.3 on 2026-04-05 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('hour', models.IntegerField()),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('occupancy_rate', models.FloatField(blank=True, null=True)),
                ('conference_room', models.FloatField(blank=True, null=True)),
                ('solar_power', models.FloatField(blank=True, null=True)),
                ('rooms_energy_kWh', models.FloatField(blank=True, null=True)),
                ('conference_energy_kWh', models.FloatField(blank=True, null=True)),
                ('laundry_energy_kWh', models.FloatField(blank=True, null=True)),
                ('kitchen_energy_kWh', models.FloatField(blank=True, null=True)),
                ('hvac_energy_kWh', models.FloatField(blank=True, null=True)),
                ('heatpump_energy_kWh', models.FloatField(blank=True, null=True)),
                ('total_energy_kWh', models.FloatField(blank=True, null=True)),
                ('grid_on', models.BooleanField(default=True)),
                ('solar_used_kWh', models.FloatField(blank=True, null=True)),
                ('grid_energy_kWh', models.FloatField(blank=True, null=True)),
                ('generator_kWh', models.FloatField(blank=True, null=True)),
                ('diesel_litres', models.FloatField(blank=True, null=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='energy_data.csvupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
